"""Matrix-driven HelixCare tests -- helixcare_discharge_matrix.json

Auto-generated by bootstrap_helixcare.py.
Exercises ALL scenarios (positive + negative + edge) from the matrix.
"""
from __future__ import annotations

import json
import time
import pytest
import httpx

from tests.nexus_harness.runner import (
    load_helixcare_matrix, scenarios_for_helixcare,
    pytest_ids, get_report, ScenarioResult, HELIXCARE_URLS,
    assert_deterministic_negative_rpc, auth_headers_for_negative_scenario,
)

MATRIX = "helixcare_discharge_matrix.json"

_positive = scenarios_for_helixcare(MATRIX, scenario_type="positive")
_negative = scenarios_for_helixcare(MATRIX, scenario_type="negative")
_edge = scenarios_for_helixcare(MATRIX, scenario_type="edge")

URLS = {
    "discharge": HELIXCARE_URLS["discharge-agent"],
    "followup": HELIXCARE_URLS["followup-scheduler"],
    "tasks/sendSubscribe": HELIXCARE_URLS["discharge-agent"],
}


def _pick_url(payload: dict) -> str:
    method = payload.get("method", "")
    for key, url in URLS.items():
        if key in method:
            return url
    return next(iter(URLS.values()))


@pytest.mark.parametrize("scenario", _positive, ids=pytest_ids(_positive))
@pytest.mark.asyncio
async def test_helixcare_discharge_positive(scenario: dict, client: httpx.AsyncClient, auth_headers: dict):
    sr = ScenarioResult(
        use_case_id=scenario["use_case_id"],
        scenario_title=scenario["scenario_title"],
        poc_demo=scenario["poc_demo"],
        scenario_type=scenario["scenario_type"],
        requirement_ids=scenario.get("requirement_ids", []),
    )
    t0 = time.monotonic()
    try:
        payload = scenario.get("input_payload", {})

        if payload.get("protocol_step") == "agent_card_get":
            for name, url in URLS.items():
                resp = await client.get(f"{url}/.well-known/agent-card.json", timeout=10.0)
                assert resp.status_code == 200, f"Agent card failed for {name}"
                card = resp.json()
                for field in payload.get("assert", []):
                    assert field in card or field in str(card), f"Missing {field}"
            sr.status = "pass"

        elif payload.get("protocol_step") == "call_rpc":
            url = next(iter(URLS.values()))
            rpc_body = {"jsonrpc": "2.0", "id": "req",
                        "method": "tasks/sendSubscribe",
                        "params": {"task": {"type": "HelixCare.SecurityTest"}}}
            resp = await client.post(f"{url}/rpc", headers=auth_headers,
                                     content=json.dumps(rpc_body), timeout=10.0)
            assert resp.status_code == 200
            body = resp.json()
            assert "result" in body, f"Expected result, got {body}"
            sr.status = "pass"

        elif payload.get("protocol_step") == "mqtt_subscribe":
            url = next(iter(URLS.values()))
            resp = await client.get(f"{url}/.well-known/agent-card.json", timeout=10.0)
            assert resp.status_code == 200
            sr.status = "pass"

        elif payload.get("jsonrpc"):
            url = _pick_url(payload)
            resp = await client.post(f"{url}/rpc", headers=auth_headers,
                                     content=json.dumps(payload), timeout=15.0)
            exp_status = scenario.get("expected_http_status", 200)
            assert resp.status_code == exp_status, f"Expected {exp_status} got {resp.status_code}"
            body = resp.json()
            expected = scenario.get("expected_result", {})
            if expected.get("ok"):
                result = body.get("result", {})
                for field in expected.get("contains", []):
                    assert field in result or field in json.dumps(result), f"Missing '{field}'"
            task_id = body.get("result", {}).get("task_id")
            if task_id and scenario.get("expected_events"):
                try:
                    async with client.stream("GET", f"{url}/events/{task_id}",
                                             headers={"Authorization": auth_headers["Authorization"]},
                                             timeout=5.0) as stream:
                        async for _ in stream.aiter_lines():
                            break
                except httpx.ReadTimeout:
                    pass
            sr.status = "pass"
        else:
            sr.status = "pass"
    except AssertionError as exc:
        sr.status = "fail"
        sr.message = str(exc)
    except Exception as exc:
        sr.status = "fail"
        sr.message = str(exc)
    finally:
        sr.duration_ms = (time.monotonic() - t0) * 1000
        get_report().add(sr)


@pytest.mark.parametrize("scenario", _negative + _edge, ids=pytest_ids(_negative + _edge))
@pytest.mark.asyncio
async def test_helixcare_discharge_negative(scenario: dict, client: httpx.AsyncClient, auth_headers: dict):
    sr = ScenarioResult(
        use_case_id=scenario["use_case_id"],
        scenario_title=scenario["scenario_title"],
        poc_demo=scenario["poc_demo"],
        scenario_type=scenario["scenario_type"],
        requirement_ids=scenario.get("requirement_ids", []),
    )
    t0 = time.monotonic()
    try:
        payload = scenario.get("input_payload", {})
        url = next(iter(URLS.values()))

        if scenario.get("scenario_type") == "edge":
            if payload.get("jsonrpc"):
                url = _pick_url(payload)
                resp = await client.post(f"{url}/rpc", headers=auth_headers,
                                         content=json.dumps(payload), timeout=15.0)
                exp_status = scenario.get("expected_http_status")
                if exp_status not in (None, ""):
                    assert resp.status_code == int(exp_status), f"Expected {exp_status} got {resp.status_code}"
                else:
                    assert resp.status_code < 500, f"Edge scenario returned {resp.status_code}"
                if "application/json" in resp.headers.get("content-type", ""):
                    body = resp.json()
                    assert isinstance(body, dict), "Expected JSON object body"
                    assert ("result" in body) or ("error" in body), "Expected JSON-RPC envelope"
            sr.status = "pass"
            return

        if payload.get("protocol_step") in ("mqtt_subscribe", "agent_card_get"):
            sr.status = "skip"
            sr.message = "Non-RPC negative scenario; deterministic JSON-RPC assertion not applicable"
        elif payload.get("protocol_step") == "call_rpc":
            rpc_body = {"jsonrpc": "2.0", "id": "req",
                        "method": "tasks/sendSubscribe", "params": {"task": {}}}
            headers = auth_headers_for_negative_scenario(scenario, auth_headers)
            resp = await client.post(f"{url}/rpc", headers=headers,
                                     content=json.dumps(rpc_body), timeout=10.0)
            body = resp.json() if "application/json" in resp.headers.get("content-type", "") else {}
            assert_deterministic_negative_rpc(
                scenario,
                status_code=resp.status_code,
                body=body if isinstance(body, dict) else {},
            )
            sr.status = "pass"
        elif payload.get("jsonrpc"):
            headers = auth_headers_for_negative_scenario(scenario, auth_headers)
            url = _pick_url(payload)
            resp = await client.post(f"{url}/rpc", headers=headers,
                                     content=json.dumps(payload), timeout=10.0)
            body = resp.json() if "application/json" in resp.headers.get("content-type", "") else {}
            assert_deterministic_negative_rpc(
                scenario,
                status_code=resp.status_code,
                body=body if isinstance(body, dict) else {},
            )
            sr.status = "pass"
        else:
            sr.status = "skip"
            sr.message = "Unsupported negative scenario shape"
    except Exception as exc:
        sr.status = "fail"
        sr.message = str(exc)
    finally:
        sr.duration_ms = (time.monotonic() - t0) * 1000
        get_report().add(sr)
